name: Deploy to Production Server

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/production/Dockerfile
          push: true
          tags: unlocktoncomputer/e-unlock-api:prod-${{ github.ref_name }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull unlocktoncomputer/e-unlock-api:prod-${{ github.ref_name }}
            docker stop e-unlock-api || true
            docker run -d --rm --name e-unlock-api -p 3333:3333 unlocktoncomputer/e-unlock-api:prod-${{ github.ref_name }}
